### PR TITLE
exposes share percentages in tooltips

### LINKED ISSUE #46: show share percentages and values in tooltips by default

### LINKED ISSUE #62: pass locale to share percentage formatAbbreviate
Dependent on https://github.com/d3plus/d3plus-common/issues/86

And then passed into `formatAbbreviate` here: https://github.com/d3plus/d3plus-hierarchy/blob/master/src/Treemap.js#L112

### PR DESCRIPTION
**Pull request by cnavarreteliz**
closes #62 
closes #46 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

**Review by davelandry — CHANGES_REQUESTED** [review]
On principal, we don't want to ever modify the user's data (even with a reserved name with underscores). That's why we wrap every data object in a sort of "d3plus" parent object (that contains `data` and `i` keys reflecting the user's original data.

In `Treemap`, this internal data array is called `shapeData`. Take the code from [this line](https://github.com/d3plus/d3plus-hierarchy/blob/master/src/Treemap.js#L112), specifically the `this._sum(d.data, d.i) / total` part and add that directly into each data object in `shapeData` as a `share` key directly after we calculate the total [here](https://github.com/d3plus/d3plus-hierarchy/blob/master/src/Treemap.js#L103).

Once that's in the internal data objects, it can be accessed for tooltips as the 3rd argument. We recently added the internal d3plus object as the 3rd argument for any user accessor function, so this should work:

```js
(d, i, x) => {
  const share = x.share;
}
```

**Comment by cnavarreteliz** [comment]
@davelandry I editted `node_modules` directly with the logic for `share`, and it doesn't work using tooltipConfig.tbody

```
tbody: (d, i, x) => {
  console.log(x)
}
```

returns this:
image

**Comment by davelandry** [comment]
@cnavarreteliz good catch! I've been playing around with this all afternoon, and I fixed some internal stuff in d3plus-tooltip and d3plus-viz that should fix this. Pull from master and see if that works!

**Comment by cnavarreteliz** [comment]
@davelandry  do I need include any additional change in the PR?

**Pull request merged**
